### ISSUE TITLE
Implement bottom_tracking velocity viewer script

### ISSUE THREAD

**Issue by jsprevost** [sonia-auv/provider_dvl#1]
For debugging purpose, it would be great to have a script that subscribe to the bottom velocities message and output a formatted NORTH - EAST viewer (can be via console or graph with arrows...).
Like this we don't have to scroll through output of rostopic echo...

**Comment by tmattio** [comment]
Would it be worth it to develop a rqt_plugin for it? In order to integrate it with a teleop software?

**Comment by jsprevost** [comment]
The goal is simply to filter the msg data to visualize only the bottom velocities quickly. It will mainly be use next test when debugging the new nav... I think we should focus on a real viewer when we will be doing the teleop software, not now...
