### ISSUE TITLE
Change the topic for the tare of the depth sensor of the DVL

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/provider_dvl#20]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Enhancement
Change the topic for taring to be the same (service) as provider_depth on AUV8. The name needs to be /provider_depth/tare.

## Current Behavior
The tare is a topic that isn't the same for both submarine and the telemetry doesn't tare the dvl on AUV7.

## Environment Used
- Project version : 1.2.0

**Comment by Kam0ss** [comment]
Using environment variable should prevent any problem.
