### ISSUE TITLE
New Provider dvl (pathfinder) or code recognition ?

### ISSUE THREAD

**Issue by alamarre3** [sonia-auv/provider_dvl#3]
need help to figure if we need a new repository for the new dvl or a new branch in the current repo with code recognition of the submarine.

**Comment by marcantoinecouture** [comment]
Sorry for the delay. I think we shouldn't have a specific branch or a specific repo for the DVL. I think we should restructure our repo the code for both. We could then add an environment variable on each submarine and use this variable in Cmakefile to compile the code for the good DVL. We could configure this environment variable with the new CLI. @gauthiermartin  what do you think of that?

**Comment by supertoto29** [comment]
Using environnement variable in the docker launch file
